version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(ci): "
    ignore:
      # We want to leave versions of rust as is.  This action is a little unique in that its version is used for the
      # rust version
      - dependency-name: "dtolnay/rust-toolchain"

  # check the core workspace
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(core): "

  # check the python sdk
  - package-ecosystem: "pip"
    directory: "/sdks/python"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(python): "

  # check the rust integration test
  - package-ecosystem: "cargo"
    directory: "integration/rust"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(rust): "