version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # check the core workspace
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  # check the python sdk
  - package-ecosystem: "pip"
    directory: "/sdks/python"
    schedule:
      interval: "weekly"