[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"

[project]
name = "bowbend"
requires-python = ">=3.8"
dependencies = [
    "cffi==1.15.1",
    "janus==1.0.0"
]

[project.optional-dependencies]
test = [
    "pytest==7.1.2",
    "pytest-asyncio==0.18.3",
    "pytest-timeout==2.1.0"
]
lint = [
    "flake8==4.0.1 ",
    "mypy==0.961",
    "pylint==2.14.4",
]

[tool.maturin]
bindings = "cffi"
sdist-include = ["target/header.h"]