[package]
name = "bowbend_core"
version = "0.1.0"
authors = ["Stuart Small <stuart.alan.small@gmail.com>"]
edition = "2018"

[dependencies]
async-stream = "0.3.2"
byteorder = "1.4"
futures = "0.3"
ipnet = "2.3"
log = "0.4"
mio = { version="0.7", features=["os-ext"] }
pin-project = "1"
pnet = "0.28"
rand = { version="0.8", features=["std", "small_rng"] }
socket2 = { version="0.4", features=["all"]}
tokio = { version="1.10", features=["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
