on:
  pull_request:
  push:
    branches:
      - main

name: Bowbend CI

jobs:
  build-release:
    name: Build Release Packages
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@1.65.0
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # TODO: We should find a way to use the cffi called out in the pyproject.toml
      - name: Install cffi and maturin
        run: pip install cffi==1.15.1 maturin==0.12.9
      - name: Build
        run: cargo xtask build --release
      - name: Check for uncommitted changes
        run: git diff --exit-code
      - name: Upload Python wheels
        uses: actions/upload-artifact@v3
        with:
          name: python-release-wheels
          path: |
            sdks/python/target/wheels/bowbend-*.whl
            sdks/python/target/wheels/bowbend-*.tar.gz
      - name: Upload Rust integration test
        uses: actions/upload-artifact@v3
        with:
          name: rust-release-integration-test
          path: |
            integration/rust/target/release/integration_test
  build-asan:
    name: Build Packages with Address Sanitizer
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-nightly-${{ hashFiles('**/Cargo.lock') }}
      # We need nightly for asan
      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # TODO: We should find a way to use the cffi called out in the pyproject.toml
      - name: Install cffi and maturin
        run: pip install cffi==1.15.1 maturin==0.12.9
      - name: Build
        run: cargo xtask build --asan
      - name: Check for uncommitted changes
        run: git diff --exit-code
      - name: Upload Python wheels
        uses: actions/upload-artifact@v3
        with:
          name: python-debug-wheels
          path: |
            sdks/python/target/wheels/bowbend-*.whl
            sdks/python/target/wheels/bowbend-*.tar.gz
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    needs: build-release
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@1.65.0
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Fetch Python wheels
        uses: actions/download-artifact@v3
        with:
          name: python-release-wheels
      - name: Install Python format tools
        run: ls bowbend-*linux*x86_64.whl | awk '{print $1"[test]"}' | xargs -0  pip install
      - name: Run unit tests
        run: cargo xtask test
  integration-test:
    name: Integration Tests
    needs: build-release
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Fetch Python wheels
        uses: actions/download-artifact@v3
        with:
          name: python-release-wheels
      - name: Start test containers
        run: ./scripts/start-test-containers.sh
      - name: Run Python integration test
        run: docker run --rm -v $(pwd):/bowbend --net test-network python:3.10 sh -c 'ls -d /bowbend/* | grep "bowbend.*linux.*whl" | xargs pip3 install && python3 /bowbend/integration/python/integration_test.py'
      - name: Fetch Rust integration test
        uses: actions/download-artifact@v3
        with:
          name: rust-release-integration-test
      - name: Run rust integration test
        run: chmod +x integration_test &&  docker run --rm -v $(pwd):/bowbend --net test-network ubuntu sh -c '/bowbend/integration_test'
  integration-test-with-asan:
    name: Integration Tests with Address Sanitizer
    needs: build-asan
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Fetch Python wheels
        uses: actions/download-artifact@v3
        with:
          name: python-debug-wheels
      - name: Start test containers
        run: ./scripts/start-test-containers.sh
      - name: Run Python integration test
        run: docker run --rm -v $(pwd):/bowbend --net test-network python:3.10 sh -c 'ls -d /bowbend/* | grep "bowbend.*linux.*whl"  | xargs  pip3 install && apt-get update && apt-get install -y libasan6 && PYTHONMALLOC=malloc LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libasan.so.6 python3 /bowbend/integration/python/integration_test.py'
  lint:
    name: Lint
    needs: build-release
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@1.65.0
        with:
          components: clippy
      - name: Fetch Python wheels
        uses: actions/download-artifact@v3
        with:
          name: python-release-wheels
      - name: Install Python lint tools
        run: ls bowbend-*linux*x86_64.whl | awk '{print $1"[lint,test]"}' | xargs -0  pip install
      - name: Run lints
        run: cargo xtask lint
  format:
    name: Format
    needs: build-release
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-nightly-${{ hashFiles('**/Cargo.lock') }}
      # We only use nightly for a couple rustfmt features
      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Fetch Python wheels
        uses: actions/download-artifact@v3
        with:
          name: python-release-wheels
      - name: Install Python format tools
        run: ls bowbend-*linux*x86_64.whl | awk '{print $1"[lint,test]"}' | xargs -0  pip install
      - name: Run lints
        run: cargo xtask format
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-stable-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust stable toolchain
        uses: dtolnay/rust-toolchain@1.65.0
      - name: Install cargo spellcheck
        run: wget -O ~/.cargo/bin/cargo-spellcheck https://github.com/drahnr/cargo-spellcheck/releases/download/v0.12.2/x86_64-unknown-linux-gnu-cargo-spellcheck-v0.12.2 && chmod +x ~/.cargo/bin/cargo-spellcheck
      - name: Run spellcheck
        run: cargo xtask spellcheck
